mv connection.management/client.must.close.connection.after.request.with.connection.close/request.rpt connection.management/client.must.close.connection.after.request.with.connection.close/client.rpt
mv connection.management/client.must.close.connection.after.request.with.connection.close/response.rpt connection.management/client.must.close.connection.after.request.with.connection.close/server.rpt
mv connection.management/client.must.not.reuse.tcp.connection.when.receives.connection.close/request.rpt connection.management/client.must.not.reuse.tcp.connection.when.receives.connection.close/client.rpt
mv connection.management/client.must.not.reuse.tcp.connection.when.receives.connection.close/response.rpt connection.management/client.must.not.reuse.tcp.connection.when.receives.connection.close/server.rpt
mv connection.management/client.with.pipelining.must.not.retry.pipelining.immediately.after.failure/request.rpt connection.management/client.with.pipelining.must.not.retry.pipelining.immediately.after.failure/client.rpt
mv connection.management/client.with.pipelining.must.not.retry.pipelining.immediately.after.failure/response.rpt connection.management/client.with.pipelining.must.not.retry.pipelining.immediately.after.failure/server.rpt
mv connection.management/server.getting.upgrade.request.must.respond.with.upgrade.header/request.rpt connection.management/server.getting.upgrade.request.must.respond.with.upgrade.header/client.rpt
mv connection.management/server.getting.upgrade.request.must.respond.with.upgrade.header/response.rpt connection.management/server.getting.upgrade.request.must.respond.with.upgrade.header/server.rpt
mv connection.management/server.must.close.connection.after.response.with.connection.close/request.rpt connection.management/server.must.close.connection.after.response.with.connection.close/client.rpt
mv connection.management/server.must.close.connection.after.response.with.connection.close/response.rpt connection.management/server.must.close.connection.after.response.with.connection.close/server.rpt
mv connection.management/server.must.close.its.half.of.connection.after.sending.response.if.it.receives.a.close/request.rpt connection.management/server.must.close.its.half.of.connection.after.sending.response.if.it.receives.a.close/client.rpt
mv connection.management/server.must.close.its.half.of.connection.after.sending.response.if.it.receives.a.close/response.rpt connection.management/server.must.close.its.half.of.connection.after.sending.response.if.it.receives.a.close/server.rpt
mv connection.management/server.should.accept.http.pipelining/request.rpt connection.management/server.should.accept.http.pipelining/client.rpt
mv connection.management/server.should.accept.http.pipelining/response.rpt connection.management/server.should.accept.http.pipelining/server.rpt
mv connection.management/server.that.is.upgrading.must.send.a.101.response/request.rpt connection.management/server.that.is.upgrading.must.send.a.101.response/client.rpt
mv connection.management/server.that.is.upgrading.must.send.a.101.response/response.rpt connection.management/server.that.is.upgrading.must.send.a.101.response/server.rpt
mv connection.management/server.that.sends.upgrade.required.must.include.upgrade.header/request.rpt connection.management/server.that.sends.upgrade.required.must.include.upgrade.header/client.rpt
mv connection.management/server.that.sends.upgrade.required.must.include.upgrade.header/response.rpt connection.management/server.that.sends.upgrade.required.must.include.upgrade.header/server.rpt
