mv client.should.send.content.length.header.in.post.even.if.no.content/request.rpt client.should.send.content.length.header.in.post.even.if.no.content/client.rpt
mv client.should.send.content.length.header.in.post.even.if.no.content/response.rpt client.should.send.content.length.header.in.post.even.if.no.content/server.rpt
mv non.http.request.to.http.server.should.be.responded.to.with.400/request.rpt non.http.request.to.http.server.should.be.responded.to.with.400/client.rpt
mv non.http.request.to.http.server.should.be.responded.to.with.400/response.rpt non.http.request.to.http.server.should.be.responded.to.with.400/server.rpt
mv robust.server.should.allow.extra.CRLF.after.request.line/request.rpt robust.server.should.allow.extra.CRLF.after.request.line/client.rpt
mv robust.server.should.allow.extra.CRLF.after.request.line/response.rpt robust.server.should.allow.extra.CRLF.after.request.line/server.rpt
mv server.must.reject.header.with.space.between.header.name.and.colon/request.rpt server.must.reject.header.with.space.between.header.name.and.colon/client.rpt
mv server.must.reject.header.with.space.between.header.name.and.colon/response.rpt server.must.reject.header.with.space.between.header.name.and.colon/server.rpt
mv server.must.reject.request.with.multiple.different.content.length/request.rpt server.must.reject.request.with.multiple.different.content.length/client.rpt
mv server.must.reject.request.with.multiple.different.content.length/response.rpt server.must.reject.request.with.multiple.different.content.length/server.rpt
mv server.should.reject.obs.in.header.value/request.rpt server.should.reject.obs.in.header.value/client.rpt
mv server.should.reject.obs.in.header.value/response.rpt server.should.reject.obs.in.header.value/server.rpt
mv server.should.send.414.to.request.with.too.long.a.request/request.rpt server.should.send.414.to.request.with.too.long.a.request/client.rpt
mv server.should.send.414.to.request.with.too.long.a.request/response.rpt server.should.send.414.to.request.with.too.long.a.request/server.rpt
mv server.should.send.501.to.unimplemented.methods/request.rpt server.should.send.501.to.unimplemented.methods/client.rpt
mv server.should.send.501.to.unimplemented.methods/response.rpt server.should.send.501.to.unimplemented.methods/server.rpt
mv server.should.send.501.to.unknown.transfer.encoding/request.rpt server.should.send.501.to.unknown.transfer.encoding/client.rpt
mv server.should.send.501.to.unknown.transfer.encoding/response.rpt server.should.send.501.to.unknown.transfer.encoding/server.rpt
mv server.should.send.status.line.in.start.line/request.rpt server.should.send.status.line.in.start.line/client.rpt
mv server.should.send.status.line.in.start.line/response.rpt server.should.send.status.line.in.start.line/server.rpt
